statefulSet:
  serviceName: service
  serviceAccountName: service-account
  replicas: 1
  containers:
    - name: postgres
      image:
        repository: postgres
        tag: "16"
      ports:
        - name: postgres
          containerPort: 5432
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
        limits:
          cpu: 500m
          memory: 1024Mi
      envFromSecret:
        - secretName: postgres-secret
          envs:
            - name: POSTGRES_PASSWORD
              key: POSTGRES_PASSWORD
      volumeMounts:
        - name: storage
          mountPath: /var/lib/postgresql/data
          subPath: postgresql
  volumes:
    - name: storage
      type: pvc
      typeName: storage-pvc

job:
  containers:
    - name: scripts
      image:
        repository: flaminel/scripts
        tag: latest
      resources:
        requests:
          cpu: 0m
          memory: 0Mi
        limits:
          cpu: 200m
          memory: 64Mi
      command:
        - /bin/bash
        - -c
        - /src/postgres/init.sh
      env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_HOST
          value: service.postgres.svc.cluster.local
      envFromSecret:
        - secretName: postgres-secret
          envs:
            - name: POSTGRES_PASSWORD
              key: POSTGRES_PASSWORD
        - secretName: authelia-secret
          envs:
            - name: AUTHELIA_USER
              key: AUTHELIA_USER
            - name: AUTHELIA_PASSWORD
              key: AUTHELIA_PASSWORD

infisicalSecrets:
  - name: infisical-postgres-secret
    serviceTokenSecretName: service-token
    secretsPath: /postgresql
    secretName: postgres-secret
  - name: infisical-authelia-secret
    serviceTokenSecretName: service-token
    secretsPath: /authelia
    secretName: authelia-secret

pvcs:
  - name: storage-pvc
    storageClassName: local-path-persistent
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    volumeMode: Filesystem

serviceAccount:
  name: service-account

services:
  - name: service
    type: ClusterIP
    ports:
      - name: postgres
        protocol: TCP
        port: 5432